server:
  port: 8002
spring:
  rabbitmq:
    addresses: 192.168.64.128:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
      order:
        exchange:
          name: spring.boot.order.exchange
          durable: true
          type: topic
          ignoreDeclarationExceptions: true
        queue:
          name: spring.boot.order.queue
          durable: true
        key: order.*