server:
  port: 8001
spring:
  rabbitmq:
    addresses: 192.168.64.128:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
